language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - pypy
  - pypy3

before_install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

install:
  - python setup.py install

script: python setup.py test
